// src/constants/permissions.js

const PERMISSIONS = {
  USER_CREATE: "USER_CREATE",
  USER_READ: "USER_READ",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  ROLE_CREATE: "ROLE_CREATE",
  ROLE_READ: "ROLE_READ",
  ROLE_UPDATE: "ROLE_UPDATE",
  ROLE_DELETE: "ROLE_DELETE",

  EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
  EMPLOYEE_READ: "EMPLOYEE_READ",
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
  EMPLOYEE_DELETE: "EMPLOYEE_DELETE",
};

module.exports = PERMISSIONS;
